"""add normalized events table

Revision ID: 4a7095a05c0b
Revises: 96818d0fc0da
Create Date: 2026-09-30 01:15:49.684664

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4a7095a05c0b'
down_revision: Union[str, None] = '96818d0fc0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalized_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), server_default=sa.text("'discussion_mention'"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('normalized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['source_event_id'],
        ['source_events.id'],
        name='fk_normalized_events_source_event_id',
    ),
    sa.ForeignKeyConstraint(
        ['technology_id'],
        ['technologies.id'],
        name='fk_normalized_events_technology_id',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'source_event_id',
        name='uq_normalized_events_source_event_id',
    )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normalized_events')
    # ### end Alembic commands ###