"""Initial setup

Revision ID: 9ae61a863f6f
Revises: 
Create Date: 2026-08-28 04:15:36.377543

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9ae61a863f6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###